#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# PhantomSDR-Plus — kernel-level flood guard (nftables)
#
# This is the layer BELOW the per-IP limits in spectrumserver. Those are exact
# but they only act once a connection has been accepted and parsed; this sheds
# volume before the server ever sees it, and it is the only layer that covers
# a peer which never speaks at all.
#
# It is deliberately blunt. The precise per-listener policy lives in
# config.toml ([limits] per_ip, per_ip_sockets, per_ip_rate); the numbers here
# sit well above those so that a normal listener can never be caught by both.
#
# Safety: the table uses `policy accept` and only drops specific abusive
# patterns, and established connections are accepted in the first rules — so
# an SSH session you are already using cannot be cut. `--apply` additionally
# arms an automatic rollback: if you do not confirm within the timeout, the
# ruleset is removed again. Nothing here can leave you locked out.
#
# Usage:
#   ./setup-firewall.sh --show      print the ruleset, change nothing
#   sudo ./setup-firewall.sh --check    syntax-check it against the kernel
#   sudo ./setup-firewall.sh --apply    load it, with a 60 s auto-rollback
#   sudo ./setup-firewall.sh --remove   delete the table
#   sudo ./setup-firewall.sh --persist  reload it at boot (systemd unit)
#   sudo ./setup-firewall.sh --status   show the table and its counters
# ---------------------------------------------------------------------------
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CFG="$HERE/admin_config.json"
TABLE="phantom_guard"
RULES="/etc/nftables.d/phantom-guard.nft"
UNIT="/etc/systemd/system/phantom-firewall.service"
ROLLBACK_S=60

# ── Ports come from admin_config.json, the same file proxy.py reads ─────────
port_from_cfg() {
    local key="$1" dflt="$2"
    [ -r "$CFG" ] || { echo "$dflt"; return; }
    python3 - "$CFG" "$key" "$dflt" <<'PY' 2>/dev/null || echo "$dflt"
import json, sys
try:
    with open(sys.argv[1]) as f:
        print(int(json.load(f).get(sys.argv[2], sys.argv[3])))
except Exception:
    print(sys.argv[3])
PY
}

PROXY_PORT="$(port_from_cfg proxy_port 8899)"
SDR_PORT="$(port_from_cfg public_port 8900)"

# ── Tunables ────────────────────────────────────────────────────────────────
# Concurrent connections per source address to the web ports. config.toml
# allows 16 sockets per address; conntrack also counts sockets still winding
# down, so this sits well above it and only catches something far outside
# normal use. The 2026-09-16 flood held 181.
MAX_CONN_PER_IP=40
# New connections per minute per source. One page load is several TCP
# connections (sockets plus asset fetches), so this is generous on purpose —
# per_ip_rate in config.toml is the precise limit, this is the volume brake.
MAX_NEW_PER_MIN=120
NEW_BURST=60
# SSH: slow brute force without ever touching an established session.
SSH_NEW_PER_MIN=10
SSH_BURST=5

generate() {
cat <<EOF
# Generated by setup-firewall.sh — edit that, not this file.
# Ports: proxy=${PROXY_PORT} sdr=${SDR_PORT}

# Idempotent prologue. Loading a table that already exists APPENDS to its
# chain rather than replacing it, so without this every reload doubles the
# ruleset — which is exactly what the systemd unit's plain "nft -f" did the
# first time round. The bare declaration creates the table when it is absent
# so that the delete below always has something to remove and never fails.
table inet ${TABLE}
delete table inet ${TABLE}

table inet ${TABLE} {
    set conn_v4 { type ipv4_addr; size 65535; flags dynamic; }
    set conn_v6 { type ipv6_addr; size 65535; flags dynamic; }
    set rate_v4 { type ipv4_addr; size 65535; flags dynamic; timeout 2m; }
    set rate_v6 { type ipv6_addr; size 65535; flags dynamic; timeout 2m; }
    set ssh_v4  { type ipv4_addr; size 4096;  flags dynamic; timeout 5m; }
    set ssh_v6  { type ipv6_addr; size 4096;  flags dynamic; timeout 5m; }

    chain input {
        # policy accept: this table only ever drops named patterns, so a rule
        # that fails to match simply lets the packet through to whatever else
        # is configured. It cannot black-hole the machine.
        type filter hook input priority -10; policy accept;

        # Anything already talking stays talking. This is first on purpose:
        # it is what makes it impossible to cut your own SSH session.
        ct state established,related accept
        iif lo accept
        ct state invalid drop

        # ── Windows file sharing: private networks only ──────────────────
        # These listen on 0.0.0.0. Whether they are reachable from outside
        # depends on the router, which this script cannot see, so they are
        # closed to the public internet here regardless.
        meta nfproto ipv4 tcp dport { 139, 445 } ip saddr != { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 } counter drop
        meta nfproto ipv4 udp dport { 137, 138 } ip saddr != { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 } counter drop

        # ── SSH brute-force brake ────────────────────────────────────────
        meta nfproto ipv4 tcp dport 22 ct state new add @ssh_v4 { ip saddr limit rate over ${SSH_NEW_PER_MIN}/minute burst ${SSH_BURST} packets } counter drop
        meta nfproto ipv6 tcp dport 22 ct state new add @ssh_v6 { ip6 saddr limit rate over ${SSH_NEW_PER_MIN}/minute burst ${SSH_BURST} packets } counter drop

        # ── Receiver ports: concurrent ceiling per source ────────────────
        meta nfproto ipv4 tcp dport { ${PROXY_PORT}, ${SDR_PORT} } ct state new add @conn_v4 { ip saddr ct count over ${MAX_CONN_PER_IP} } counter drop
        meta nfproto ipv6 tcp dport { ${PROXY_PORT}, ${SDR_PORT} } ct state new add @conn_v6 { ip6 saddr ct count over ${MAX_CONN_PER_IP} } counter drop

        # ── Receiver ports: new-connection rate per source ───────────────
        meta nfproto ipv4 tcp dport { ${PROXY_PORT}, ${SDR_PORT} } ct state new add @rate_v4 { ip saddr limit rate over ${MAX_NEW_PER_MIN}/minute burst ${NEW_BURST} packets } counter drop
        meta nfproto ipv6 tcp dport { ${PROXY_PORT}, ${SDR_PORT} } ct state new add @rate_v6 { ip6 saddr limit rate over ${MAX_NEW_PER_MIN}/minute burst ${NEW_BURST} packets } counter drop
    }
}
EOF
}

need_root() {
    [ "$(id -u)" -eq 0 ] || { echo "This needs root: sudo $0 $*" >&2; exit 1; }
}

case "${1:---show}" in
  --show)
    generate
    ;;

  --check)
    need_root "$@"
    tmp="$(mktemp)"; generate > "$tmp"
    if nft -c -f "$tmp"; then echo "✔ ruleset is valid"; else echo "✖ ruleset rejected"; rm -f "$tmp"; exit 1; fi
    rm -f "$tmp"
    ;;

  --apply)
    need_root "$@"
    tmp="$(mktemp)"; generate > "$tmp"
    nft -c -f "$tmp" || { echo "✖ ruleset rejected — nothing loaded"; rm -f "$tmp"; exit 1; }

    nft delete table inet "$TABLE" 2>/dev/null || true
    nft -f "$tmp"
    mkdir -p "$(dirname "$RULES")"; cp "$tmp" "$RULES"; rm -f "$tmp"
    echo "✔ loaded (proxy=${PROXY_PORT} sdr=${SDR_PORT})"
    echo

    # Auto-rollback. If this shell dies, or you simply say nothing, the table
    # goes away again — so a rule that turns out to block something important
    # can only do so for as long as the timeout.
    ( sleep "$ROLLBACK_S"
      if [ -f /run/phantom-firewall.confirmed ]; then exit 0; fi
      nft delete table inet "$TABLE" 2>/dev/null || true
      rm -f "$RULES"
      echo "" >&2
      echo "⏱  no confirmation — ruleset rolled back." >&2 ) &
    rollback_pid=$!

    rm -f /run/phantom-firewall.confirmed
    echo "Check now, from ANOTHER terminal or device, that:"
    echo "  · the receiver still loads   (http://<host>:${PROXY_PORT}/)"
    echo "  · you can still open a new SSH session"
    echo
    # Accepts y / yes in any case, matching ask_yn() in the installers. Anything
    # else — including saying nothing, or the timeout expiring — rolls back,
    # because the safe answer has to be the one you get by doing nothing.
    read -r -t "$ROLLBACK_S" -p "Keep these rules? [y/N] (${ROLLBACK_S}s, ENTER = roll back): " ans || ans=""
    echo
    if [[ "${ans:-}" =~ ^[Yy] ]]; then
        touch /run/phantom-firewall.confirmed
        kill "$rollback_pid" 2>/dev/null || true
        echo "✔ kept. Survive a reboot with: sudo $0 --persist"
    else
        kill "$rollback_pid" 2>/dev/null || true
        nft delete table inet "$TABLE" 2>/dev/null || true
        rm -f "$RULES"
        echo "↩ rolled back, nothing is loaded."
    fi
    ;;

  --remove)
    need_root "$@"
    nft delete table inet "$TABLE" 2>/dev/null && echo "✔ table removed" || echo "· table was not loaded"
    rm -f "$RULES"
    systemctl disable --now phantom-firewall.service 2>/dev/null || true
    rm -f "$UNIT"; systemctl daemon-reload 2>/dev/null || true
    ;;

  --persist)
    need_root "$@"
    [ -f "$RULES" ] || { echo "Nothing to persist — run --apply first." >&2; exit 1; }
    cat > "$UNIT" <<EOF
[Unit]
Description=PhantomSDR-Plus nftables flood guard
After=network-pre.target
Wants=network-pre.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/sbin/nft -f ${RULES}
ExecStop=/usr/sbin/nft delete table inet ${TABLE}

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable --now phantom-firewall.service
    echo "✔ will reload at boot (phantom-firewall.service)"
    ;;

  --status)
    need_root "$@"
    nft list table inet "$TABLE" 2>/dev/null || echo "· table not loaded"
    ;;

  *)
    echo "usage: $0 [--show|--check|--apply|--remove|--persist|--status]" >&2
    exit 1
    ;;
esac
