/**
 * js8-tables.js — GENERATED by jsdsp/js8_wasm/extract_js8_varicode.py.
 * Do not edit by hand; re-run the generator instead.
 *
 * Derived from JS8Call (https://github.com/js8call/js8call), GPL-3.0.
 * PhantomSDR-Plus is GPL-3.0, so this is license-compatible.
 */

/** Alphabet the 72 payload bits are grouped into, 6 bits per character. */
export const ALPHABET72 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-+/?.";

/** Callsign and grid alphabet (38 characters + one extra slot at index 38). */
export const ALPHANUMERIC = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ /@";

export const NBASECALL = 262177560;
export const NBASEGRID = 32400;
export const NUSERGRID = 32410;
export const NMAXGRID  = 32767;

/** i3bit is a bitfield, not a frame type (varicode.h). */
export const I3_FIRST = 1;   // first frame of a message
export const I3_LAST  = 2;   // last frame of a message
export const I3_DATA  = 4;   // raw data frame, no frame-type header

/** Frame types, held in the first 3 bits of the 72-bit payload. */
export const FRAME_HEARTBEAT         = 0;
export const FRAME_COMPOUND          = 1;
export const FRAME_COMPOUND_DIRECTED = 2;
export const FRAME_DIRECTED          = 3;
export const FRAME_DATA              = 4;  // 10X
export const FRAME_DATA_COMPRESSED   = 6;  // 11X

/** Special callsign values, stored as offsets from NBASECALL. */
export const BASECALLS = new Map([
  [NBASECALL + 1  , "<....>"],
  [NBASECALL + 2  , "@ALLCALL"],
  [NBASECALL + 3  , "@JS8NET"],
  [NBASECALL + 4  , "@DX/NA"],
  [NBASECALL + 5  , "@DX/SA"],
  [NBASECALL + 6  , "@DX/EU"],
  [NBASECALL + 7  , "@DX/AS"],
  [NBASECALL + 8  , "@DX/AF"],
  [NBASECALL + 9  , "@DX/OC"],
  [NBASECALL + 10 , "@DX/AN"],
  [NBASECALL + 11 , "@REGION/1"],
  [NBASECALL + 12 , "@REGION/2"],
  [NBASECALL + 13 , "@REGION/3"],
  [NBASECALL + 14 , "@GROUP/0"],
  [NBASECALL + 15 , "@GROUP/1"],
  [NBASECALL + 16 , "@GROUP/2"],
  [NBASECALL + 17 , "@GROUP/3"],
  [NBASECALL + 18 , "@GROUP/4"],
  [NBASECALL + 19 , "@GROUP/5"],
  [NBASECALL + 20 , "@GROUP/6"],
  [NBASECALL + 21 , "@GROUP/7"],
  [NBASECALL + 22 , "@GROUP/8"],
  [NBASECALL + 23 , "@GROUP/9"],
  [NBASECALL + 24 , "@COMMAND"],
  [NBASECALL + 25 , "@CONTROL"],
  [NBASECALL + 26 , "@NET"],
  [NBASECALL + 27 , "@NTS"],
  [NBASECALL + 28 , "@RESERVE/0"],
  [NBASECALL + 29 , "@RESERVE/1"],
  [NBASECALL + 30 , "@RESERVE/2"],
  [NBASECALL + 31 , "@RESERVE/3"],
  [NBASECALL + 32 , "@RESERVE/4"],
  [NBASECALL + 33 , "@APRSIS"],
  [NBASECALL + 34 , "@RAGCHEW"],
  [NBASECALL + 35 , "@JS8"],
  [NBASECALL + 36 , "@EMCOMM"],
  [NBASECALL + 37 , "@ARES"],
  [NBASECALL + 38 , "@MARS"],
  [NBASECALL + 39 , "@AMRRON"],
  [NBASECALL + 40 , "@RACES"],
  [NBASECALL + 41 , "@RAYNET"],
  [NBASECALL + 42 , "@RADAR"],
  [NBASECALL + 43 , "@SKYWARN"],
  [NBASECALL + 44 , "@CQ"],
  [NBASECALL + 45 , "@HB"],
  [NBASECALL + 46 , "@QSO"],
  [NBASECALL + 47 , "@QSOPARTY"],
  [NBASECALL + 48 , "@CONTEST"],
  [NBASECALL + 49 , "@FIELDDAY"],
  [NBASECALL + 50 , "@SOTA"],
  [NBASECALL + 51 , "@IOTA"],
  [NBASECALL + 52 , "@POTA"],
  [NBASECALL + 53 , "@QRP"],
  [NBASECALL + 54 , "@QRO"],
]);

/** Directed command number -> display text. Several names share a
  * number; JS8Call resolves that with QMap::key(), which returns the
  * FIRST key in sorted order, so that is what is stored here. */
export const DIRECTED_CMDS = new Map([
  [ -1, " CQ"],
  [  0, " SNR?"],
  [  1, " DIT DIT"],
  [  2, " NACK"],
  [  3, " HEARING?"],
  [  4, " GRID?"],
  [  5, ">"],
  [  6, " STATUS?"],
  [  7, " STATUS"],
  [  8, " HEARING"],
  [  9, " MSG"],
  [ 10, " MSG TO:"],
  [ 11, " QUERY"],
  [ 12, " QUERY MSGS"],
  [ 13, " QUERY CALL"],
  [ 14, " ACK"],
  [ 15, " GRID"],
  [ 16, " INFO?"],
  [ 17, " INFO"],
  [ 18, " FB"],
  [ 19, " HW CPY?"],
  [ 20, " SK"],
  [ 21, " RR"],
  [ 22, " QSL?"],
  [ 23, " QSL"],
  [ 24, " CMD"],
  [ 25, " SNR"],
  [ 26, " NO"],
  [ 27, " YES"],
  [ 28, " 73"],
  [ 29, " HEARTBEAT SNR"],
  [ 30, " AGN?"],
  [ 31, " "],
]);

/** 41-character alphabet used by the message checksums. */
export const ALPHABET = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+-./?";
export const NALPHABET = 41;

/** Per-submode tolerance, in Hz, for grouping frames into one message.
  * From JS8Submode.cpp; indexed Normal, Fast, Turbo, Slow, Ultra. */
export const RX_THRESHOLD_HZ = [10, 16, 32, 10, 50];

/** T/R CYCLE in seconds, same submode order. Slot scheduling aligns to this. */
export const SUBMODE_PERIOD_S = [15, 10, 6, 30, 4];

/** Seconds of transmission -- how much audio each slot must capture. */
export const SUBMODE_TXDUR_S = [15, 10, 6, 28, 4];

/** Submode names, same order. */
export const SUBMODE_NAMES = ["Normal", "Fast", "Turbo", "Slow", "Ultra"];

/** Commands that open a buffer and wait for following data frames. */
export const BUFFERED_CMDS = new Set([5, 9, 10, 11, 12, 13, 15, 24]);

/** Buffered commands whose assembled text ends with a checksum, and its size. */
export const CHECKSUM_CMDS = new Map([[5, 16], [9, 16], [10, 16], [11, 16], [12, 16], [13, 16], [15, 0], [24, 16]]);

/** JS8Call UI defaults: end-of-transmission and message-frame-idle markers. */
export const EOT = "♢";
export const MFI = "……";

/** Commands whose extra field carries an SNR rather than a plain number. */
export const SNR_CMDS = new Set([25, 29]);

/** Character Huffman table for plain data frames: code string -> character. */
export const HUFF_DECODE = new Map([
  ["01"       , " "],
  ["100"      , "E"],
  ["0011"     , "A"],
  ["1101"     , "T"],
  ["00000"    , "R"],
  ["00011"    , "H"],
  ["10100"    , "S"],
  ["10111"    , "N"],
  ["11100"    , "I"],
  ["11111"    , "O"],
  ["000011"   , "Y"],
  ["000101"   , "G"],
  ["001001"   , "F"],
  ["001011"   , "W"],
  ["101011"   , "M"],
  ["101101"   , "U"],
  ["110001"   , "C"],
  ["110011"   , "L"],
  ["111011"   , "D"],
  ["0000100"  , "5"],
  ["0000101"  , "3"],
  ["0001000"  , "Z"],
  ["0001001"  , "2"],
  ["0010000"  , "Q"],
  ["0010001"  , "1"],
  ["0010100"  , "J"],
  ["0010101"  , "0"],
  ["1010100"  , "X"],
  ["1010101"  , "\""],
  ["1011000"  , "!"],
  ["1011001"  , "?"],
  ["1100000"  , "+"],
  ["1100001"  , "-"],
  ["1100100"  , "K"],
  ["1100101"  , "V"],
  ["1110100"  , "."],
  ["1111001"  , "B"],
  ["1111011"  , "P"],
  ["11101010" , "/"],
  ["11101011" , "7"],
  ["11110000" , "6"],
  ["11110001" , "8"],
  ["11110100" , "9"],
  ["11110101" , "4"],
]);
